# Generated by Django 5.1.3 on 2024-11-23 20:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tome',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.tome')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('arabic_word', models.CharField(max_length=200)),
                ('french_word', models.CharField(max_length=200)),
                ('quiz_success', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.lesson')),
            ],
        ),
    ]
